# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6769c68ccac31775a2ed35bb2bbf04ed3b577d1e0d42e0a67f958689406edeafd23d9e8f0abe61bb785772f310a5ff1890b30d5a85c83f2bdbb3c123f97497

test:
  secret_key_base: d584f2a3c5ebdc41564160505817df312a912e91305b2b9995516c5a51461f0d9bedda897b143000be90d87bf7646f378ef03cf13468f3f722137187d9cc9f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
